```{r}
library(tidyverse)

#Function for finding the slope coefficient 
find_mdl_coefficient <- function(x,y){
  coef(summary(lm(y~x)))[2,1]
}

#Function for finding the slope coefficient confidence interval
find_mdl_coefficient_ce <- function(x,y){
  lin_mod <- lm(y~x)
  std_err <- coef(summary(lin_mod))[2,2]
  df <- length(residuals(lin_mod))
  crit_t <- abs(qt(0.05/2, df))
  (crit_t * std_err)
}


cell_lines <- as.character(unique(df_scaled$cells))



plot_ces <- function(cmpnd, assay){
  y_lines <- vector()
  y_pvals <- vector()
  x_lines <- vector()
  x_pvals <- vector()
  
  df_slopes <- 
    df_scaled %>% 
    group_by(cells, compound, group) %>% 
    summarise(slope = find_mdl_coefficient(treatment, response),
              slope_err = find_mdl_coefficient_ce(treatment,response)) %>% 
    mutate(slope_min = slope-slope_err, slope_max=slope+slope_err) 
  
  df_test <- 
    df_slopes %>% 
    filter(compound == cmpnd) %>% 
    separate(group, into=c("condition", "exposure_time"), sep=" - ")

  df_test <- 
    df_test %>% 
    group_by(cells, exposure_time) %>% 
    mutate(z_val = diff(slope) / sqrt(sum(slope_err^2)), pval_x = mean(slope)) %>% 
    mutate(p_val = pnorm(abs(z_val), lower.tail = FALSE) * 2)
  
    df_test <-
    df_test %>% 
    unite(group, condition, exposure_time, sep= " - ") %>% 
    mutate(group = factor(group, levels = c("Normoxia - 24 Hours", "Hypoxia - 24 Hours",
                                              "Normoxia - 48 Hours", "Hypoxia - 48 Hours"))) %>% 
    arrange(group)
  
   
  #Calculate the z score for the different between hypoxia and normoxia at 24 hours
  # twentyfour.dif.z <- 
  #   df_slopes_cmpnd %>% 
  #   filter(group == 'Normoxia - 24 Hours' | group == 'Hypoxia - 24 Hours') %>% 
  #   group_by(cells) %>% 
  #   summarise(z_val = diff(slope) / sqrt(sum(slope_err^2)), pval_y = mean(slope)) 
  # 
  # twentyfour.dif.z <-
  #   twentyfour.dif.z %>% 
  #   mutate(p_val = pnorm(abs(z_val), lower.tail = FALSE) * 2)
  

  
  #Calculate the p-vale for that score
  # twentyfour.df.p <- pnorm(abs(twentyfour.dif.z$z_val), lower.tail = FALSE) * 2
  # 
  
  #Calculate the z score for the different between hypoxia and normoxia at 48 hours
  # fortyeight.dif.z <- 
  #   df_slopes_cmpnd %>% 
  #   filter(group == 'Normoxia - 48 Hours' | group == 'Hypoxia - 48 Hours') %>%
  #   summarise(z_val = diff(slope) / sqrt(sum(slope_err^2)), pval_x = mean(slope))
  
  
  #Calculate the p-vale for that score
  # fortyeight.df.p <- pnorm(abs(fortyeight.dif.z$z_val), lower.tail = FALSE) * 2
  
  
  # title <- sprintf("Slope Confidence Intervals for %s - %s (%s)", cell_line, cmpnd, assay)
  # dir <- sprintf("../../Graphs/%s/SlopesCEs", cell_line)
  # dir.create(dir, showWarnings = FALSE)
  # file_name <- sprintf("%s/%s_%s_%s_CE.png", dir, cell_line, cmpnd, assay)
  # 
  # y_lines <- c(rbind(df_slopes_cmpnd$slope_min, df_slopes_cmpnd$slope_max))
  # y_pvals <- rep(c(twentyfour.dif.z$pval_x, twentyfour.dif.z$pval_x,
  #                  fortyeight.dif.z$pval_x, fortyeight.dif.z$pval_x), each=2)
  # 
  # x_lines <- rep((seq(from = nrow(df_slopes_cmpnd), to = 1, by=-1)/2) + i - 1, each=2)
  # x_pvals <- rep((c(3.5,1.5)/2) + i-1, each=4)
  # 
  # y_dots <- rep(df_slopes_cmpnd$slope, each=2)
  # x_dots <- 
  # lbls <- rep(round(as.numeric(c(twentyfour.df.p, twentyfour.df.p, fortyeight.df.p, fortyeight.df.p)), digits = 5), each=2)
  # lbls <- lapply(lbls, function(x){
  #   if (x < 0.05){
  #     return (sprintf("p = %s *", x))
  #   } else{
  #     return (sprintf("p = %s", x))
  #   }
  # })
  # group <- rep(df_slopes_cmpnd$group, each = 2)
  # df_lines <- 
  #   data.frame(x=x_lines, y=y_lines, group=group) 
    
  df_test_2 <-
    df_test 
  
  # plt <-
  #   ggplot(data=df_test2) + 
  #   geom_line(aes(x=group, y=)) + 
  #   geom_text(aes(x=x_pvals, y=y_pvals, label=lbls),color='black') +
  #   geom_point(y=y_dots, color="black") +
  #   labs(x="Regression Slopes 95% Confidence Intervals", y="", color="Condition - Exposure Time",
  #        title=title) +
  #   theme_bw() +
  #   theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),
  #         panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
  # print(plt)
  plt <-
    ggplot(data=df_test_2) +
    geom_errorbar(aes(x=group, ymin=slope_min, ymax=slope_max, colour=group, width=0), size=1.5, alpha=0.6) +
    geom_point(aes(x=group, y=slope), size=2) + 
    facet_wrap(~cells, strip.position = "bottom", scales = "free_x") +
    theme_bw()

  
  print(plt)
#ggsave(file_name, device = "png", height=3)
  
}

plot_ces("DEP", "LDH")
#plot_ces("Ox66", "LDH")
#plot_ces("DEP + Ox66", "LDH")
```

```{r}
library(tidyverse)
file_path= "../../Data/Compiled/LDH_ALL_Except_A549.csv"
df <- read.csv(file_path)
df <- 
  df %>% 
  mutate(treatment = str_replace(treatment, "Blank", "0 ug/ml"),
         treatment = str_replace(treatment, "20 ug/ml \\+ 50 ppm", "70 ug/ml"),
         treatment = str_replace(treatment, "50 ug/ml \\+ 100 ppm", "150 ug/ml"),
         treatment = str_replace(treatment, "100 ug/ml \\+ 200 ppm", "300 ug/ml")) %>% 
  separate(treatment, into=c("treatment", "units"), sep=" ") %>% 
  mutate(treatment = as.numeric(treatment)) %>% 
  select(-units) %>% 
  unite(group, condition, exposure_time, sep=" - ")

df_scaled <- df
```

